### ISSUE TITLE
akka.ActorLogging interferes with persist.ActorLogging for FSMs

### ISSUE THREAD

**Issue by emanresusername** [nestorpersist/logging#6]
```text
overriding method log in trait ActorLogging of type => akka.event.LoggingAdapter;
[error]  lazy value log in trait ActorLogging of type com.persist.logging.Logger has weaker access privileges; it should be public
[error] class Actor extends FSM[State, Data] with ActorLogging {
```

**Comment by emanresusername** [comment]
[this](https://github.com/emanresusername/logging/commit/082c361fffcef2c8c6d7c39b4ba1c6baaf21f1a6) mostly got around it for me, though i hit problems right after, not sure if they're related yet.
Anyway, i'm sure this isn't the most robust/ideal workaround but providing it in the hopes it's a helpful start

**Comment by nestorpersist** [comment]
I plan to add trait AltActorLogging that is like ActorLogging but defines altLog rather than log.
This will be part of the Scala 2.12 update that I plan to do later this week.
This will solve the name conflict problem when using Akka FSM.
